include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"

image: ${UBUNTUIMAGE}:20.04

.prep-image: &prep-image |
    apt update; DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends gcc zlib1g-dev valgrind

stages:
    - test
    - release

build:
    stage: test
    before_script:
        - *prep-image
    script:
        - make fastcat
        - ./fastcat --help
        - make mem_check

conda:
    extends: .deploy-conda
    before_script:
        - cd conda
        - *prep-image
    only:
        - tags

