include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"
    - project: "epi2melabs/ci-templates"
      file: "snippets.yaml"

image: ${UBUNTUIMAGE}:20.04

variables:
    GIT_SUBMODULE_STRATEGY: recursive


.prep-image: &prep-image |
    DEBIAN_FRONTEND=noninteractive
    apt update -qq
    apt install -y --no-install-recommends gcc autoconf valgrind make curl wget zlib1g-dev libbz2-dev libreadline-dev libssl-dev libffi-dev liblzma-dev libcurl4-gnutls-dev

stages:
    - test
    - prerelease
    - release

build:
    stage: test
    before_script:
        - *prep-image
    script:
        - make fastcat
        - ./fastcat --help
        - make mem_check_fastcat
        - make bamstats
        - ./bamstats --help
        - make mem_check_bamstats

deploy-checks:
    stage: prerelease
    script:
        - !reference [.check, argp-c-version]
        - !reference [.check, changelog]
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/'


conda:
    extends: .deploy-conda
    before_script:
        - *prep-image
        - export CONDA_PKG=${CI_PROJECT_NAME}
        - export CONDA_PKG_VERSION=${CI_COMMIT_TAG/v/}
        - cd conda

conda-mac:
    extends: .deploy-conda-mac
    before_script:
        - export CONDA_PKG=${CI_PROJECT_NAME}
        - export CONDA_PKG_VERSION=${CI_COMMIT_TAG/v/}
        - cd conda
