include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"
    - project: "epi2melabs/ci-templates"
      file: "snippets.yaml"

image: ${UBUNTUIMAGE}:20.04

variables:
    GIT_SUBMODULE_STRATEGY: recursive


.prep-image: &prep-image |
    DEBIAN_FRONTEND=noninteractive
    apt update -qq
    apt install -y --no-install-recommends gcc autoconf automake valgrind make curl wget zlib1g-dev libbz2-dev libreadline-dev libssl-dev libffi-dev liblzma-dev libcurl4-gnutls-dev

stages:
    - test
    - prerelease
    - release

build:
    stage: test
    before_script:
        - *prep-image
    artifacts:
      when: always
      paths:
        - test/*
    script:
        - make fastcat
        - ./fastcat --help
        - make mem_check_fastcat
        - make mem_check_fastcat_demultiplex
        - make regression_test_fastcat
        - make regression_test_sam_to_fastcat
        - make bamstats
        - ./bamstats --help
        - make mem_check_bamstats
        - make mem_check_bamstats_duplex
        - make test_bamstats_badNM
        - make bamindex
        - ./bamindex build --help
        - make mem_check_bamindex

deploy-checks:
    stage: prerelease
    script:
        - !reference [.check, argp-c-version]
        - !reference [.check, changelog]
        - export LICENSE_FILE="BSD-4-CLAUSE"
        - !reference [.check, license]
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/'


.before-script: &before-script |
    export CONDA_PKG=${CI_PROJECT_NAME}
    export CONDA_PKG_VERSION=${CI_COMMIT_TAG/v/}
    cd conda

conda:
    extends: .deploy-conda
    before_script:
        - *prep-image
        - *before-script

conda-arm:
    extends: .deploy-conda-linux-arm
    before_script:
        - *prep-image
        - *before-script

conda-mac:
    extends: .deploy-conda-mac
    before_script:
        - *before-script

conda-mac-arm:
    extends: .deploy-conda-mac-arm
    before_script:
        - *before-script

test-conda-arm:
    stage: test
    extends: .deploy-conda-linux-arm
    variables:
        UPLOAD: "no"
    before_script:
        - *prep-image
        - *before-script
    rules:
    - if: $CI_COMMIT_BRANCH != null
