include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"

image: ${UBUNTUIMAGE}:20.04

.prep-image: &prep-image |
    apt update; apt install -y gcc zlib1g-dev

stages:
    - test
    - release

build:
    stage: test
    before_script:
        - *prep-image
    script:
        make fastcat
        ./fastcat -h

conda:
    extends: .deploy-conda
    before_script:
        - cd conda
        - *prep-image
    only:
        - tags

