include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"

image: ${UBUNTUIMAGE}:20.04

stages:
    - test
    - release

conda:
    extends: .deploy-conda
    before_script:
        - cd conda
        - apt update; apt install -y zlib1g-dev
    only:
        - branches

