package:
  name: {{ environ.get('CONDA_PKG') }}
  version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - argp-standalone # [osx]
        # not sure why zlib needs to be explicitly listed here,
        # bioconda::samtools does it too, and conda build can't find it otherwise
        # despite it getting installed into the build env
        - htslib >=1.20,<1.22  # ignore htslib 1.22 for now until CRAM 3.1 dust settles
        - zlib
        - xz
    run:
        - htslib >=1.20,<1.22  # ignore htslib 1.22 for now until CRAM 3.1 dust settles
        - zlib
        - xz
test:
    commands:
        fastcat --help
        bamstats --help
        bamindex build --help

about:
    home: "https://github.com/epi2me-labs/fastcat"
    license: Mozilla Public License 2.0 
    license_family: OTHER
    license_file: LICENSE
    summary: "Concatenate fast/a/q/gz and calculate basic statistics"
    doc_url: https://github.com/epi2me-labs/fastcat
    dev_url: https://github.com/epi2me-labs/fastcat 

extra:
    recipe-maintainers:
        - cjw85

