package:
  name: {{ environ.get('CONDA_PKG') }}
  version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - nanoporetech::htslib =1.19.1
    host:
        - argp-standalone # [osx]
        # linked to all the same stuff as bioconda builds
        - nanoporetech::htslib =1.19.1
    run:
        - nanoporetech::htslib =1.19.1
test:
    commands:
        fastcat --help
        bamstats --help
        bamindex build --help

about:
    home: "https://github.com/epi2me-labs/fastcat"
    license: Mozilla Public License 2.0 
    license_family: OTHER
    license_file: LICENSE
    summary: "Concatenate fast/a/q/gz and calculate basic statistics"
    doc_url: https://github.com/epi2me-labs/fastcat
    dev_url: https://github.com/epi2me-labs/fastcat 

extra:
    recipe-maintainers:
        - cjw85

